import './globals.css';
import '@radix-ui/themes/styles.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Theme } from '@radix-ui/themes';
import Header from '@/components/header/header';
import ToasterProvider from '@/components/providers/toaster_provider';
import { AuthProvider } from '@/components/providers/auth_context';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
{/*         <Theme> */}
          <AuthProvider>
            <ToasterProvider />
            <Header />
            {children}
          </AuthProvider>
{/*         </Theme> */}
      </body>
    </html>
  );
}
